# -*- coding: utf-8 -*-
"""final_fp_finger.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zDTnqrdXdtPOZrya4KeCVTSPbqxeI_wM
"""

import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

import os
import cv2

import matplotlib.pyplot as plt

import joblib

model=joblib.load('//content//drive//MyDrive//fp_model_finger.joblib')

xtest=cv2.imread('//content//1__M_Left_index_finger.BMP', cv2.IMREAD_GRAYSCALE)

img_resize = cv2.resize(xtest, (96, 96))
img_resize = img_resize.reshape(1, 96, 96, 1)
img_resize=img_resize/255

predictions = model.predict(img_resize)

print(predictions)

predicted = [np.argmax(predictions) ]

print(predicted)

predicted=np.array(predicted)
print(predicted.ndim)
print(predicted)

if predicted[0]==0:
     print("thumb")

elif predicted[0]==1:
         print("index",end=" ")

elif predicted[0]==2:
         print("middle",end=" ")

elif predicted[0]==3:
         print("ring",end=" ")

elif predicted[0]==4:
         print("little",end=" ")

matching_accuracy=predictions[0][predicted]*100
print(matching_accuracy[0])

with open('matching_accuracy_finger.txt', 'w') as file:
    print(matching_accuracy[0], file=file)

with open('finger.txt', 'w') as file:
  if predicted[0]==0:
     print("thumb", file=file)

  elif predicted[0]==1:
         print("index", file=file)

  elif predicted[0]==2:
         print("middle", file=file)

  elif predicted[0]==3:
         print("ring", file=file)

  elif predicted[0]==4:
         print("little", file=file)